### ISSUE TITLE
QBeat: Install multiple mods using wildcards/modlist

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#14]
'making the list numbered and letting you do like --install "1-5 6 9-11" would be amazing'

That, or wildcards, or read a file contianing the list of mods to install/validate/update/etc

**Comment by Zamundaaa** [comment]
And/Or simply listing the mods like so: ./QBeat --install "Custom Sabers" "SongBrowser" "SaberTailor"

Also I just tried QBeat on Manjaro and it all worked very well, except for Beat Saber crashing on exit (I assume that's a mods fault) but as it's on exit it doesn't really matter to me.
Looking forward to some kind of UI!
Thank you for all your work on this :smile:

**Comment by geefr** [comment]
Can now do ./Qbeat --install foo bar baz "bizzle with spaces"

I'll leave it at that, seems to work well enough
