### ISSUE TITLE
QBeat binaries are linked to Qt 5.11 - Don't work on Mint 19.1

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#22]
Looks like Mint 19.1 has Qt 5.9 in the package manager, so the current binaries won't work

Either need to package Qt with the release, or build binaries against an older copy for the time being

Workaround is to install a copy of Qt 5.11+ on your system and make sure it's in the library path, alternatively build qbeat from source.

**Comment by wmmc88** [comment]
same issue with ubuntu 18.04

**Comment by geefr** [comment]
Rejecting as QBeat is deprecated. Beataroni launches correctly on Mint 19, seems to operate correctly.
