### ISSUE TITLE
Scripts claim sucessful install but no mods installed

### ISSUE THREAD

**Issue by lordkitsuna** [geefr/beatsaber-linux-goodies#31]
I have been trying to get this working for awhile now, i removed beatsaber entirely, deleted all files. installed, ran once, ran the wine scripts, then i run the patcher and install mods all of which it says worked but when opening the game its just a normal game with no mods. I am not sure how to figure out what is wrong since it claims everything went just fine 
![Screenshot_20191116_170256](https://user-images.githubusercontent.com/3444267/69001504-8521fa80-0894-11ea-853b-39ea28262bc4.png)
also those errors about themes are annoying idk if those can be removed

**Comment by geefr** [comment]
The icon errors I've never encountered before, but you're also using kde by the looks of it so likely that's related..

If you can let me know the following it would help:
- What's the output of './QBeat --config get'
- What distro are you running
- Can you double-check that <bsInstall>/Plugins contains the mod dlls
- What's the output of './QBeat --validate-all'

The fact that it reports success means IPA.exe thinks it managed to patch the game correctly.
Maybe try 'install method 2' from the main readme - Using beatdrop to download the mods would help work out if it's the mod downloads (unlikely) or the patching process itself (likely).

For testing I like to install just BSIPA and BSIPA Mod List, which should be enough to put a 'mods' button on the game's menu.

**Comment by lordkitsuna** [comment]
`[kitsuna@kitsuna-desktop QBeat-Alpha-9]$ ./QBeat --config get
bsInstall : /home/kitsuna/Games/steamapps/common/Beat Saber/
bsProtonDir : /home/kitsuna/.steam/steam/steamapps/common/Proton 4.11
gameType : steam
gameVersion : 1.5.0
winePrefix : /home/kitsuna/Games/steamapps/compatdata/620980/pfx/
[kitsuna@kitsuna-desktop QBeat-Alpha-9]$ 
`
Distro is Arch and the /Plugins folder is populated

`winePrefix : /home/kitsuna/Games/steamapps/compatdata/620980/pfx/
[kitsuna@kitsuna-desktop QBeat-Alpha-9]$ ./QBeat --validate-all
Icon theme "gnome" not found.
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
File: IPA.exe Expected: f4e2b516f048ef6cd0cec90830aa25bc Got: f4e2b516f048ef6cd0cec90830aa25bc
File: IPA.exe.config Expected: 113aab26517f62b45112e50b3889e63e Got: 113aab26517f62b45112e50b3889e63e
File: IPA/Data/Managed/I18N.West.dll Expected: a75f9881a0e9b61ad1d02bdba0406468 Got: a75f9881a0e9b61ad1d02bdba0406468
File: IPA/Data/Managed/I18N.dll Expected: aa156a789840ef85e6c0fd08b27a18a6 Got: aa156a789840ef85e6c0fd08b27a18a6
File: IPA/Data/Managed/IPA.Injector.dll Expected: 9e0b2c41373db4a92be81d2ace85db01 Got: 9e0b2c41373db4a92be81d2ace85db01
File: IPA/Data/Managed/IPA.Injector.pdb Expected: c41c68f98ea97fa7c7609d27bd102f87 Got: c41c68f98ea97fa7c7609d27bd102f87
File: IPA/Data/Managed/IPA.Loader.dll Expected: 36060e4ff60b92ace16a82b73a091581 Got: 36060e4ff60b92ace16a82b73a091581
File: IPA/Data/Managed/IPA.Loader.pdb Expected: 793c246fa3dca04cad8ab7838128a584 Got: 793c246fa3dca04cad8ab7838128a584
File: IPA/Data/Managed/IPA.Loader.xml Expected: a167ee06f60cc153d581ae9617c81c05 Got: a167ee06f60cc153d581ae9617c81c05
File: IPA/Data/Managed/Microsoft.CSharp.dll Expected: a8f13d4df59ebbcae3d07daaeab739af Got: a8f13d4df59ebbcae3d07daaeab739af
File: IPA/Data/Managed/System.Runtime.Serialization.dll Expected: c739259c418dad08468a4def4c4d1486 Got: c739259c418dad08468a4def4c4d1486
File: IPA/Libs/0Harmony.1.2.0.1.dll Expected: e11a2fa00d46a40c485b41126cd7d1c8 Got: e11a2fa00d46a40c485b41126cd7d1c8
File: IPA/Libs/Ionic.Zip.1.9.1.8.dll Expected: 6ded8fcbf5f1d9e422b327ca51625e24 Got: 6ded8fcbf5f1d9e422b327ca51625e24
File: IPA/Libs/Mono.Cecil.0.10.4.0.dll Expected: bda5cf9930c3bb1976c7484c7f280cba Got: bda5cf9930c3bb1976c7484c7f280cba
File: IPA/Libs/Mono.Cecil.Mdb.0.10.4.0.dll Expected: df8837d3efdaa1405200f529f06f36b1 Got: df8837d3efdaa1405200f529f06f36b1
File: IPA/Libs/Mono.Cecil.Pdb.0.10.4.0.dll Expected: aeff6fb43e6604178e905465463eb546 Got: aeff6fb43e6604178e905465463eb546
File: IPA/Libs/Mono.Cecil.Rocks.0.10.4.0.dll Expected: b1de908243feac14049ddeefb858ef33 Got: b1de908243feac14049ddeefb858ef33
File: IPA/Libs/Newtonsoft.Json.12.0.0.0.dll Expected: 4df6c8781e70c3a4912b5be796e6d337 Got: 4df6c8781e70c3a4912b5be796e6d337
File: IPA/Libs/SemVer.1.2.0.0.dll Expected: f0a2d65976e56446c84578e8b8030a34 Got: f0a2d65976e56446c84578e8b8030a34
File: IPA/winhttp.dll Expected: f25171a12e8b375164ea79c09730e931 Got: f25171a12e8b375164ea79c09730e931
File: Libs/CommonMark.0.1.0.0.dll Expected: e39cd45b2e0390c91b34651c7dd0f7d7 Got: e39cd45b2e0390c91b34651c7dd0f7d7
File: Libs/CommonMark.0.1.0.0.pdb Expected: ddf1c6232c9cc337e6ef9edf65bc76ab Got: ddf1c6232c9cc337e6ef9edf65bc76ab
File: Plugins/BSIPA-ModList.dll Expected: 6d3039a032924c1871970392fa8f4018 Got: 6d3039a032924c1871970392fa8f4018
File: Plugins/BSIPA-ModList.pdb Expected: dc9eba80977d7e8bf2ad7e80b2eecff2 Got: dc9eba80977d7e8bf2ad7e80b2eecff2
File: Beat Saber_Data/CustomLevels/One More Time/Credits.txt Expected: 93cec86e3b549340ddf24f28d7d643de Got: 93cec86e3b549340ddf24f28d7d643de
File: Beat Saber_Data/CustomLevels/One More Time/Easy.dat Expected: 3393e2608d34b401552ca6a60080736f Got: 3393e2608d34b401552ca6a60080736f
File: Beat Saber_Data/CustomLevels/One More Time/Expert.dat Expected: 9525c71ca72035a6fa504057703b89c5 Got: 9525c71ca72035a6fa504057703b89c5
File: Beat Saber_Data/CustomLevels/One More Time/Hard.dat Expected: 0c70a4984eb35a8daa95c0c3194fc2b6 Got: 0c70a4984eb35a8daa95c0c3194fc2b6
File: Beat Saber_Data/CustomLevels/One More Time/Normal.dat Expected: 803a07231d1c145cbb37723c97f0d4d8 Got: 803a07231d1c145cbb37723c97f0d4d8
File: Beat Saber_Data/CustomLevels/One More Time/One More Time.ogg Expected: ec27d43f54564ef29faf311b07f1685c Got: ec27d43f54564ef29faf311b07f1685c
File: Beat Saber_Data/CustomLevels/One More Time/cover.jpg Expected: 270bd9b51e076395c37b83406ef84877 Got: 270bd9b51e076395c37b83406ef84877
File: Beat Saber_Data/CustomLevels/One More Time/info.dat Expected: 42aafe4bf7d773a0f3c770b5ef76b890 Got: 42aafe4bf7d773a0f3c770b5ef76b890
File: Beat Saber_Data/CustomLevels/One More Time/lyrics.srt Expected: ace00a2d13e1e44ece3e6139ae20e14f Got: ace00a2d13e1e44ece3e6139ae20e14f
File: Plugins/SongCore.dll Expected: dc235f0aa5892c98c4585c633fd15cfc Got: dc235f0aa5892c98c4585c633fd15cfc
File: songe-converter.exe Expected: 7253bc715fa4f5bc1e06970e70ffee6b Got: 7253bc715fa4f5bc1e06970e70ffee6b
File: CustomSabers/Neo Katanas.saber Expected: 7e7481fba3835ac2135cdaaa168721c9 Got: 7e7481fba3835ac2135cdaaa168721c9
File: CustomSabers/Oldschool_Default.saber Expected: 6a868eae666e6078e63f206303fa3f9e Got: 6a868eae666e6078e63f206303fa3f9e
File: CustomSabers/Plasma_Katana.saber Expected: 1983c967d86188d5d618ddd73eec06d9 Got: 1983c967d86188d5d618ddd73eec06d9
File: CustomSabers/Tesla Sabers V3.0.saber Expected: fc46d31da615bd9551c8d7a10cdd971c Got: fc46d31da615bd9551c8d7a10cdd971c
File: Plugins/CustomSaber.dll Expected: f388684bfb8b15009d4b52e9095dcc36 Got: f388684bfb8b15009d4b52e9095dcc36
File: Plugins/SongDataCore.dll Expected: 9346201cb7b1904a086934e784927590 Got: 9346201cb7b1904a086934e784927590
File: Libs/INIFileParser.2.5.2.0.dll Expected: 2e77f841dbf271fd1ffc460bfd87a1d5 Got: 2e77f841dbf271fd1ffc460bfd87a1d5
File: Plugins/IniParser.manifest Expected: dc75233a258ed6fb7a7b4f1899db9426 Got: dc75233a258ed6fb7a7b4f1899db9426
File: Plugins/BS_Utils.dll Expected: eac32b163ded1a47b4f7970c4bb25bf5 Got: eac32b163ded1a47b4f7970c4bb25bf5
File: Plugins/BeatSaberCustomUI.dll Expected: e39069c205f74fa39803792938b7e55e Got: e39069c205f74fa39803792938b7e55e
File: Plugins/BeatSaberCustomUI.xml Expected: fd2c08187c21b2a2e02f6265f70621fa Got: fd2c08187c21b2a2e02f6265f70621fa
File: Plugins/EnhancedSearchAndFilters.dll Expected: 3b278fbffe59db39ddd2eb060e610376 Got: 3b278fbffe59db39ddd2eb060e610376
File: Plugins/SongBrowser.dll Expected: 53be3286e444eba40996d56c41fa9a44 Got: 53be3286e444eba40996d56c41fa9a44
SUCCESS: All mods valid
`

I did just notice when i open BS there is a message about a .net application not being able to run. just a generic "This application could not be started" message

**Comment by lordkitsuna** [comment]
Nevermind i figured it out, i forgot that as part of the process i needed to change beatsaber to the custom proton version. Mods are now showing up.

**Comment by geefr** [comment]
Alright, easy-ish problem then

It might be possible to make qbeat update the steam settings for that. Otherwise if my docs aren't clear enough let me know
