### ISSUE TITLE
Link in readme file returns 404

### ISSUE THREAD

**Issue by Toby4213** [geefr/beatsaber-linux-goodies#34]
In the main README.md file the link to the QBeat Docs leads to a 404 error. [https://github.com/geefr/beatsaber-linux-goodies/tree/QBeat/QBeat](https://github.com/geefr/beatsaber-linux-goodies/tree/QBeat/QBeat)

**Comment by geefr** [comment]
Thanks for pointing it out, either a mistake or github changed their url syntax..
