### ISSUE TITLE
Release packaging

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#37]
Need to package 3rd party deps like Qt into the release, or put together an appimage/similar release.

As it stands QBeat works out of the box, but only if the system has minizip/Qt of a sufficient versions. 

Qt is kinda awkward to package, if anyone has advice please comment ;)

**Comment by ashkitten** [comment]
just wanted to say i've put together something for myself with nix, if that is in any way useful: https://github.com/ashkitten/nixos-config/blob/master/packages/QBeat/default.nix

**Comment by geefr** [comment]
Thanks, it might be useful but I can't tell. Is Nix something folks can install on other distributions or specific to NixOS?

I think the end solution for this was either going to be .deb/.rpm packages to cover the main cases, or an appimage (but dependency management of Qt is kinda a pain).

Turns out I'm really busy this year anyway so might not do much myself on QBeat - More than happy to merge improvements if this would work for others?

**Comment by ashkitten** [comment]
nix is a package manager that can be used on any distro. i haven't verified that it works elsewhere (and the automatic wineprefix setup does *not* work - it tries to fetch its own winetricks or something) but theoretically it should be fine (most things are unless they deal with graphics drivers)

**Comment by geefr** [comment]
Ah okay, so it's similar to snap/pip/whatever, cool.

I'll bear this in mind if I'm working on packaging then, or if you've got the time I'd be happy to add QBeat into nix properly.

For the wine thing - There's rumours that it's not needed any more, at least not the whole custom copy of proton...It's always been the biggest hack in all of this and it's difficult to test.

**Comment by ashkitten** [comment]
we tend not to add unreleased things to nixpkgs, that can definitely happen once this hits 1.0 though. if you can make it not rely on setting up a wineprefix (or just let it use the system's winetricks) that would work great.

**Comment by geefr** [comment]
Closing as QBeat is deprecated. Beataroni is much more self-contained, should provide a neater base for any packaging setups.
