### ISSUE TITLE
ERROR: Unable to find mod named: BSIPA

### ISSUE THREAD

**Issue by pwaller** [geefr/beatsaber-linux-goodies#39]
Hi! Thanks for doing this. Just wanted to let you know if a minor usability issue I'm hitting, as a new user of beatsaber and QBeat.

While following the [first time setup instructions](https://github.com/geefr/beatsaber-linux-goodies/blob/ddf49b6e092b06c39e023d00af20081006214022/QBeat/README.md#first-time-setup), I hit the error `ERROR: Unable to find mod named: BSIPA`.

Luckily, I'm a technical user, so I hacked on the source code and discovered that the requested URL was:

https://beatmods.com/api/v1/mod?status=approved&gameVersion=1.9.0&name=BSIPA

And the returned value for that URL was:

```
[]
```

QBeat's behaviour in this case was quite confusing, it took me a little while to figure out what was going on. Of course, if I change the version to 1.8.0, then it will presumably find the mod.

The version I have happens to be 1.9.0, and I didn't realise it was so new until now (April 9th).

**Comment by geefr** [comment]
Hey, thanks for letting me know.

Think there's 2 possibilities here - either no mods are ready for 1.9 yet, or it happens to be compatible with 1.8 (You'd have to check with the support folks).

Think mod assistant does something clever with version numbers but qbeat most certainly doesn't.
If you can confirm the 1.8 mods are still compatible, then just run ./QBeat --config set gameVersion "1.8.0" and continue as normal (Will set qbeat to download all mods at v1.8).

If that's not working check out the scripts folder; They're what qbeat uses underneath and are the reference if you need to manually hack things (I hear the custom wine prefix isn't needed any more, hadn't verified that one yet)

**Comment by pwaller** [comment]
Yeah, I still didn't have much luck. I tried to install "camera plus" with gameVersion 1.8.0 (even though I have 1.9.0 installed), and everything with QBeat appeared to "work" (no errors), but when I launched "Proton BeatSaber", I couldn't find any evidence that the mod was installed and functioning.

**Comment by geefr** [comment]
Hm, admitedly I haven't touched QBeat in months, so it was only a matter of time before something broke.

This is on my todo list, hopefully I'll have time over the next week

**Comment by gyroninja** [comment]
I am using Beat Saber 1.9.0 and QBeat worked for me once setting the version to 1.8.0. I installed the ScoreSaber and BeatSaverDownloader mods and both of them seemed to work fine.

**Comment by geefr** [comment]
Okay yeah this is just beatmods not listing anything for 1.9, sounds like it was another minor update that didn't break mod compatibility.

If anyone knows how mod assistant works out the version number I'll be happy to take a pr/etc, ideally something that doesn't need manual maintenance (Probably quite easy if done in beatmods backend, but whatever).

Made a small update to the readme for now, anyone running 1.9.0 should set QBeat to 1.8.0
