### ISSUE TITLE
Check if all hacks are still needed

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#40]
Seen a couple of rumours that need investigating
- The custom wine prefix may not be needed now, due to fixes in bsipa
- There was something in the mod assistant changelogs about linux fixes, would be worth checking those out

(If anyone has the time to help here please do, and let me know how it goes)

**Comment by jcc10** [comment]
Tried a clean install with the Mod Manager from beatmods.com Needed .net 6.1 to work. Displayed two black windows for me.

I'm going to stick with this for now.

**Comment by geefr** [comment]
Did some testing here, and the custom proton copy isn't needed.
So it's down to these steps:
- Make sure wine has .net support
- Patch pfx/user.reg to include winhttp=native,builtin - Without this beat saber seems to fail to load textures (They're not using the http dll for file access right? That would be weird).

I'll issue a new release shortly + update the docs here, but seems other than the wine prefix update there's really nothing needed (So maybe modassistant could work out the box now, cool)
