### ISSUE TITLE
How to update.

### ISSUE THREAD

**Issue by jcc10** [geefr/beatsaber-linux-goodies#42]
I was wondering if there was a recommended way to re-patch post update. I have tried just re-running the commands

```bash
./QBeat --install "BSIPA"
./QBeat --patch
```

And copying in a backup of the mods but the mods don't show up. I have checked and it is set to the right compat-tool.

**Comment by geefr** [comment]
Honestly? The easiest option is to reinstall, I know it's not ideal but it's what I tested for
But things should work fine without a clean reinstall, just make sure
- Set the bs version to the same version Mod Assistant uses (Sometimes it's not the same as the game version..)
- Launch the game once without mods, using the stock compatibility tool
- Re-patch + install as normal
- Don't copy over old mods unless you know they're compatible with the new game version - Mod Assistant has some funky backup/migration logic around this but qbeat definitely doesn't ;)

It's quite possible you don't need the custom wine prefix now, haven't verified that myself yet though so let me know if it works.
