### ISSUE TITLE
.NET installer gets stuck due to yama

### ISSUE THREAD

**Issue by C0rn3j** [geefr/beatsaber-linux-goodies#44]
```
 echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
```
The script should just do above as on some systems the installer will get stuck after 4.0 is setup, never getting to 4.6.1.

EDIT: actually it still seems like the rest of the installer gets stuck (4.5 forwards), so am probably just getting lucky with the 4.0 installs and the variable is unrelated.

**Comment by C0rn3j** [comment]
For people getting stuck in the .NET install phase on the killing part as is shown here:
![image](https://user-images.githubusercontent.com/1641362/88313083-44c42780-cd13-11ea-9725-f09e6a8f85f2.png)

I filtered by .exe in htop and killed everything related to .NET, then the installer kept moving. Otherwise it'd be permanently stuck.

**Comment by geefr** [comment]
How strange..I've had the installers take a long time before, but never hang outright, thanks for the info.
