### ISSUE TITLE
Donwloading Songs doesnt work

### ISSUE THREAD

**Issue by AlbertMerker** [geefr/beatsaber-linux-goodies#46]
Downloaded Songs don't appear in the custom song list.
Problem is probably allready known, i guess.

**Comment by geefr** [comment]
Not sure what you mean - QBeat and the scripts don't allow song downloads, just mods.

Or do you mean the song list mod doesn't work? Would double check if it works on windows first in that case, my stuff just downloads the zips and extracts em ;)

**Comment by AlbertMerker** [comment]
ah, yes yes :D sorry, i actually didn't know if you are even involved in programming the mods.
just had to move the songs from the directory ../Beats Saber/Beat Saber_Data/CustomLevels/*
to ../Beats Saber/Beat Saber_Data/Random Songs/
can't test it right now on windows. but thanks anyway!

**Comment by geefr** [comment]
Nope, I don't have time to develop mods, just provided the installer for Linux.

Best place for mod questions is the wiki/discord server: https://bsmg.wiki/
