### ISSUE TITLE
Failed to install .Net 4.6.1

### ISSUE THREAD

**Issue by Ominitay** [geefr/beatsaber-linux-goodies#47]
Upon running `./QBeat --setup-wine`, the installation fails at installing .Net 4.6.1. Logs are tiny so I'll post it here:

```Running wine setup script. Please be patient and choose the default option in all of the setup wizards. A status message will be printed once setup is complete
Executing: /hddhome/Games/beatsaber-modding/bs-linux-setup-wine.sh
Script execution failed: 
Executing mkdir -p /home/renami
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 57c09343a9a09359b7f7556113f36670037a3d860848113283a36f34b9388562 with wine-5.15 and WINEARCH=win64
Executing w_do_call dotnet461
Executing mkdir -p /home/renami
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet461 
ERROR: Failed to install .Net 4.6.1

FAILURE: Setup of wine prefix failed

**Comment by geefr** [comment]
Yay! Those logs just mean winetricks failed for some reason, if winetricks didn't output anything more useful it'll be a pain to work out what's wrong.

I'll need more info on your setup
- what distro are you running?
- what version of wine?
- What did you set the winePrefix to? (./QBeat --config get)
- Is this an old wine install?
- Did lots of installer UIs appear during the process (It can take a really long time)
- Did you click next/follow through the installers accepting the default options?

**Comment by Ominitay** [comment]
I am running a minimal install of Arch (kernel is 5.8.5-arch1-1). Wine version is 5.16-1. QBeat winePrefix is ~/.wine (a new directory, not in use by anything else. I only reinstalled Arch due to other reasons a few days ago, so it is definitely a new Wine install. Iirc, no installer UIs appeared at all.

**Comment by mtfurlan** [comment]
Looks like this is being tracked at https://github.com/Winetricks/winetricks/issues/1596

**Comment by Ominitay** [comment]
I changed the script to use the fixed(?) version of Winetricks, (in [#1599](https://github.com/Winetricks/winetricks/pull/1599)), and the script seems to get further, but still fails. Logs pasted [here](https://pastebin.com/uEuzwD9B).

**Comment by geefr** [comment]
Looks like it ran winetricks okay so you might have a valid setup. I'll admit the detection of whether .net is installed is quite rudimentary in QBeat.

I think if you run QBeat --patch it doesn't actually require the validate-wine script to pass, so might just go ahead and work regardless.
If not if you open up the scripts and just set them to exit 0 after installing wine/when trying to validate it should continue and try to run IPA.exe anyway.

Another test would be if you can open ModAssistant using that copy of wine - If it'll open then IPA should also work correctly

**Comment by Ominitay** [comment]
Oh, I _may_ have got it working, as I am getting an installer window now! I'll keep you posted.

**Comment by Ominitay** [comment]
I had to restart the setup again, because I accidentally terminated my terminal emulator. Is it normal for the installer window for dotnet to finish, and to be left with over 100 mscorsvw.exe processes? Should I wait for them to complete, or has something failed?

**Comment by Ominitay** [comment]
Now there are over 600 and growing, filling up my 16GiB RAM and 16GiB swap :worried:

**Comment by Ominitay** [comment]
The script says that the wine prefix is valid, but IPA.exe crashes when I run ./QBeat --patch, so I presume the prefix wasn't setup fully/correctly.

**Comment by Ominitay** [comment]
I've remade the prefix, running `pkill mscorsvw.exe` after each installer finishes running. The installer said that the Wine prefix was valid again, but I still can't get `./QBeat --patch` to work. This time, there isn't even an error window, only the command line errors. [https://pastebin.com/ZLNeFhgc](https://pastebin.com/ZLNeFhgc)

**Comment by Ominitay** [comment]
Oh, ignore that it wasn't working, I had set the Beat Saber location to the wrong drive. It has patched successfully now. It may be worth adding to the readme to `pkill mscorsvw.exe` after each installer, otherwise it can cause that catastrophic runaway which completely blocks an install. Also, it might be a good idea to amend the script to use the fixed version of winetricks for the time being, until the PR is merged.

**Comment by Ominitay** [comment]
About 770 mscorsvw.exe processes were created after the first installer, which filled up the entirety of my system's memory. This caused the system to crash, interrupting the setup. This made `./QBeat --patch` fail every time, despite the script assuming that the wine prefix was intact. The solution was to run `pkill mscorsvw.exe` after each installer finishes running. This fixed the issue with a runaway number of processes crashing the system.
It may be worth adding to the readme to `pkill mscorsvw.exe` after each installer, otherwise it can cause that catastrophic runaway which completely blocks an install. Also, it might be a good idea to amend the script to use the fixed version of winetricks for the time being, until the PR is merged.

**Comment by geefr** [comment]
Oookay. Thanks for working it out.

I won't actively change things right now but if there's a PR I'd probably merge it.
Default run would still need to use current winetricks, I won't have time to monitor/revert the change later but adding a workaround env var or similar would be fine, already got a few of those in for ssl errors/similar.

Unless this affects every user that is. In short if ubuntu/mint users get this then I'll merge whatever is needed to make qbeat work.

**Comment by mtfurlan** [comment]
It's an issue with the bash logic, so it will effect everyone installing dotnet stuff.
I expect it to be fixed in winetricks pretty soon though, the issue was opened 9 days ago and the testing branch from a dev is from 3 days ago.

**Comment by Ominitay** [comment]
I've made a PR (#48) adding a variable to override the default script. :smiley:

**Comment by geefr** [comment]
Thanks again to the both of you, please shout when there's more issues/etc.
