### ISSUE TITLE
Wine: dotnet461 installation

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#5]
Seems like this will be the sticking point for several things
- If the user has to install .net, why wouldn't they just use mod assistant through wine
- winetricks takes ages to install stuff
- Users probably have wine in some form, there's no knowing what's in their prefix

For now will try scripting the installation of .net into the script (unless there's some override argument to say use the system wine?)

Should check whether Microsoft's redist can be used inside wine - winetricks seems to spend a long time installing other things before the final .net runtime

Ideal solution would be to port ipa over to mono/.net core..

**Comment by geefr** [comment]
@Zamundaaa  https://github.com/geefr/beatsaber-linux-goodies/blob/script-install-dotnet461/scripts/bs-linux-modfix.sh

This is a tweaked version of the script that:
- makes sure your system has wine/requirements
- makes a standalone wine prefix for running IPA.exe
- Installs .net as needed to run it
- Does the rest of the hacks for beat saber

Fairly sure I don't want this all in one script going forward, as not everyone will want to wait for .net to install (It takes a while, hit enter in the terminal once all the windows have stopped as the script might keep spamming afterwards for some reason)

Likely it'd be a check in beatdrop/similar to ensure the system has what's needed, and if not calls out to something like this to setup just enough to run ipa.

Did give porting ipa to .net core a quick try and it might be possible, just very difficult.

**Comment by Zamundaaa** [comment]
It installs dotnet461 just fine. It creates the custom wine prefix and the extra proton version but then fails.
`
Creating custom Proton installation for Beat Saber use
mv: cannot stat '/../../compatdata/620980/pfx/drive_c/windows/syswow64/winhttp.dll': No such file or directory
/run/media/xaver/HUGE_DATA/Games/SteamLibraries/WVR/steamapps/common/Beat Saber ~/git
0009:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x10021a79, 0x1006ed50, 0x1006ed68) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x100042e1, 28) stub
0009:fixme:ntdll:EtwEventRegister ({319dc449-ada5-50f7-428e-957db6791668}, 0x917be8, 0xd9e678, 0xd9e690) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x76ec3a, 28) stub
0009:fixme:kernelbase:QuirkIsEnabled3 (0034F520, FFFFFFFF) stub!
0009:fixme:process:GetNumaHighestNodeNumber (0x34fc58): semi-stub
0009:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0xa17a92, 0xd9d368, 0xda70a8) stub.
0009:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 0xa17a92, 0xd9d6d8, 0xd9d578) stub.
0009:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 0xa17a92, 0xda5c98, 0xda70b8) stub.
0009:fixme:ntdll:EtwEventRegister ({cc2bcbba-16b6-4cf3-8990-d74c2e8af500}, 0xa17a92, 0xd9d480, 0xd9d4c8) stub.
0009:fixme:wer:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 0x750000) stub!
002c:err:ole:CoGetContextToken apartment not initialised
0009:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 4 00193084 0034BEAC 0034C518 00000000
0009:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 001930A8 0034C09C 0034C708 00000000
0009:fixme:combase:RoGetParameterizedTypeInstanceIID stub: 3 001930A8 0034C09C 0034C708 00000000
0009:fixme:path:parse_url failed to parse L"System.Core"
0009:fixme:path:parse_url failed to parse L"System"
0009:fixme:path:parse_url failed to parse L"System.Configuration"
0009:fixme:path:parse_url failed to parse L"System.Xml"
0009:fixme:path:parse_url failed to parse L"System.Numerics"
0009:fixme:path:parse_url failed to parse L"System.Security"
0009:fixme:path:parse_url failed to parse L"System"
0009:fixme:nls:LocaleNameToLCID unsupported flags 8000000
0009:fixme:nls:LCIDToLocaleName unsupported flags 8000000
0009:fixme:nls:get_dummy_preferred_ui_language (0x8 0x34d49c (nil) 0x34d498) returning a dummy value (current locale)
0009:fixme:nls:get_dummy_preferred_ui_language (0x8 0x34d49c 0x193b38 0x34d498) returning a dummy value (current locale)
0009:fixme:path:parse_url failed to parse L"System.Windows.Forms"
0009:fixme:path:parse_url failed to parse L"System.Drawing"
0009:fixme:path:parse_url failed to parse L"Accessibility"
0009:fixme:path:parse_url failed to parse L"System.Deployment"
0009:fixme:path:parse_url failed to parse L"System.Runtime.Serialization.Formatters.Soap"
0009:fixme:path:parse_url failed to parse L"System.Drawing"
0009:fixme:nls:LCMapStringEx unsupported lparam 19c910
0009:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x34f14c, 0x1a6010, 0x34f150, 0x34f144
0009:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0x34f14c, 0x1a6010, 0x34f150, 0x34f144
0009:fixme:time:GetCalendarInfoEx (L"en-US", 1, (nil), 0x20000030, (nil), 0, 0x1251954): semi-stub
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 2
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 4
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
0009:fixme:time:GetCalendarInfoW Unimplemented caltype 57
Restoring old version...`

**Comment by geefr** [comment]
Huh..

The error from mv isn't an issue, just means you've run the script before and I haven't redirected the output to null

To me that just looks like ipa has failed for some reason.
One thing to try is just to run the script again, I found sometimes ipa can be a bit unreliable (could have just been me)

Otherwise looks like I've got to test on more systems (so far just Mint 19), let me know the details and I'll see if I can reproduce here:
 - So what distro are you using?
 - What does 'wine --version' give
 - Is there anything in your environment that would mess with the wine/proton prefixes? (Other than what the script uses internally)

The good news is you should have a functional copy of wine, so you might be able to debug further with this:
`WINEPREFIX=/home/.wine/wineprefix/beatsaber-linux-goodies-ipa wine IPA.exe`

**Comment by Zamundaaa** [comment]
It looks like it worked nontheless. I started Beat Saber and the UI mod was there, along with song loader. Then the UI broke and I restarted the game. Boom, all mods I installed there and working perfectly.
I'm on Manjaro KDE (testing). Wine is on 4.15. I don't think there's anything changed from Wine but the install I got is pretty old, might be something I did once and forgot about.

**Comment by geefr** [comment]
Awesome, sounds like all the basic building blocks are there and it's mainly usability issues to deal with for a functional release.

I think ipa has some fairly sensible return values for success/failure. I'll see about hiding the wine debug output and making a clear message at the end. Think we can just check if winhttp.dll is in the right place and the return code to check it worked correctly.

**Comment by geefr** [comment]
Closing this one - 0.3 has scripts for setting up wine and checking if the right stuff is present
