### ISSUE TITLE
QXcbConnection: XCB error

### ISSUE THREAD

**Issue by Ominitay** [geefr/beatsaber-linux-goodies#51]
When running QBeat commands, there is always an error at the top. As far as I can tell, the script works fine besides this, but it may be worth looking into what causes it. It is always the same error: `qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 450, resource id: 0, major code: 20 (GetProperty), minor code: 0`. Thank you for the great script!

**Comment by geefr** [comment]
Thanks, it'll be some incompatibility between the qt version i built for and what you're running against (Managing dependencies for qt is a nightmare tbh).

Assuming everything else works then I wouldn't worry too much about this, given that qbeat is actually command line only still I'm tempted to rewrite it in rust sometime and drop the Qt dependency entirely ;)

**Comment by Ominitay** [comment]
I've just got all of the qt5 packages which came with KDE, so I may be missing a few packages :woman_shrugging:

**Comment by Ominitay** [comment]
Should I leave this open or just close it?

**Comment by geefr** [comment]
Leave it open, as it's understandable as a bug. Better to have an open list of issues than hide them.

The platform/native integration stuff in qt seems to change quite drastically in minor releases (and the 5.8 -> 5.12 series was a pretty major rework for qt, despite not being a major update)

**Comment by geefr** [comment]
Closing this one, is still a bug with QBeat, but Beataroni won't have it (I hope)
