### ISSUE TITLE
Read list of bs versions from beatmods

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#62]
As implemented for the tui script in #60 but in the main qbeat binary
* Users should only be able to set versions from this list
* Default version should be the latest
* Should add a version-upgrade command to qbeat to register against the latest version, and re-patch - Would be good to auto upgrade and preserve all mods if possible, or do something like modassistant with moving the old mods to a backup folder.

**Comment by Ominitay** [comment]
In terms of the functionality, I suggest that two commands for the version are implemented. `getVersions`, and `setVersion`. 
`getVersions` should do exactly what it sounds like: output an array of all accepted versions. The API already outputs a JSON array, so this could perhaps be passed on, maybe changed to be more user-readable.
`setVersion` should accept either a value from `getVersions`, or accept the value `latest`, which would, obviously, set it to the latest version.
Doing things this way would ensure that QBeat remains non-interactive.

**Comment by geefr** [comment]
Functionality is implemented in beataroni so closing. Would accept pr for qbeat but extremely low priority.
