### ISSUE TITLE
Sort out Linux IPA build/packaging

### ISSUE THREAD

**Issue by geefr** [geefr/beatsaber-linux-goodies#72]
IPA link: https://github.com/bsmg/BeatSaber-IPA-Reloaded/issues/55

Currently there's a one-off build of IPA just thrown into this repo. This is bad for many reasons.
In some form need to:
- have a proper repo for the fork - Unknown whether it'll be a direct link/fork back to BSIPA, or just a copy of the relevant code sections. Port did require significant hacks, so may not be mergable back to BSIPA repo
- Doesn't need to be a separate executable. Could be packaged into beataroni as dll/classes.
- Separate executable would be useful for other projects/power users - Should provide builds for exe as well as libs
- Needs to respect version numbers (currently it's set to 1.0.0.1 or something)
- 'context IPA path is wrong' - There's some path that's incorrect when it runs, can't fully remember what the post-it was related to but the code is a mess regardless

**Comment by geefr** [comment]
For now will be a standalone fork, containing parts of BSIPA. repo here: https://github.com/geefr/BSIPA-Linux
Will be added as a submodule + lib somehow into this repo, to be used in beataroni

**Comment by geefr** [comment]
Current state is BSIPA-Linux can be built as binary or library, and can be called as part of Beataroni.
Should add in error handling around the call, and otherwise clean things up
* Any stdout/err output from IPA itself dumps to the console at the moment
* If IPA crashes it terminates Beataroni
* Beataroni can't detect if IPA returns a non-zero result
* Had to add an extra command line flag (--relativeToPwd) to get things working for now, this should be dropped if possible

**Comment by ominitay** [comment]
> For now will be a standalone fork, containing parts of BSIPA. repo here: https://github.com/geefr/BSIPA-Linux
> Will be added as a submodule + lib somehow into this repo, to be used in beataroni

This will work well; GitHub API allows one to grab artefacts from releases.

**Comment by geefr** [comment]
Just wrapping this up and calling it done. As always shout if there's any issues and such.
