### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by viasux** [geefr/beatsaber-linux-goodies#86]
New version of beat saber was released on march 12th.

**Comment by ominitay** [comment]
That's nothing to do with this tool...

**Comment by geefr** [comment]
@AverytheFurry Cool, I haven't played in a while ;)

If mod assistant works but my installer doesn't - That's a bug
If mod assistant doesn't work, or the mods themselves haven't been updated - Nothing I can do, be patient

**Comment by viasux** [comment]
> @AverytheFurry Cool, I haven't played in a while ;)
> 
> If mod assistant works but my installer doesn't - That's a bug
> If mod assistant doesn't work, or the mods themselves haven't been updated - Nothing I can do, be patient

I'm on linux, so I don't think I can run mod assistant.

When trying to install, it told me to "check that I selected the right version," but the right version was not an option

**Comment by geefr** [comment]
Okay, that means beatmods doesn't list that version yet (Or they list in a 2nd/3rd place again and have a wonky api).

Best head over to the beatmods discord - If folks say things work fine I'll take a look (sometime over the next week)

**Comment by ominitay** [comment]
The project doesn't store the versions of the game; it fetches them from the BeatMods API. It takes a bit for the API to update, so it's safe to close this issue.

**Comment by Vash63** [comment]
This can definitely be closed, I just used it on the latest version of Beat Saber and it worked fine.
