### ISSUE TITLE
Feature Request: Show description label for each mod

### ISSUE THREAD

**Issue by Vash63** [geefr/beatsaber-linux-goodies#88]
Would be nice if in addition to the mod's title it showed the description so you would know what a mod does prior to installing it.

**Comment by geefr** [comment]
Hah, that would be fairly useful, it's been added to the todo list.

Expect an update/release at some point, feel free to chase if there's no progress by say 2022 ;)

**Comment by geefr** [comment]
Should be addressed by https://github.com/geefr/beatsaber-linux-goodies/releases/tag/1.2.1

I haven't tested heavily, so shout if there's any issues.

**Comment by Vash63** [comment]
Works great for me, thanks
