### ISSUE TITLE
Beatsaber 1.16.3 no mods

### ISSUE THREAD

**Issue by B3ATDROP3R** [geefr/beatsaber-linux-goodies#90]
Linux 5.10.49-1-MANJARO #1 SMP PREEMPT Sun Jul 11 12:59:43 UTC 2021 x86_64 GNU/Linux
Beataroni just gives me an empty mod list when ran. Not sure what other info to give.

**Comment by CrispyPin** [comment]
Same problem on POP os 20.10, this only happens since beat saber 1.16.3

**Comment by geefr** [comment]
Hiya, can you just confirm that:
- 1.16.3 is a recent release
- Mods have been ported to the new version
- Mod assistant / windows mod managers are showing mods
- Do mods show up if you select an earlier game version in Beataroni?

Assuming there are mods available to download I'll try and take a look over the weekend.

**Comment by CrispyPin** [comment]
Ah my bad, turns out none of the mods have updated yet, I thought at least some of them wouldn't need any work. Beataroni works as expected if I select an older version instead.

**Comment by geefr** [comment]
One would think if the version is published there would be mods, but that would be sensible ;)

Common occurence then, please be patient, help out the mod devs if you can in any way.
Ticket will remain open for a while to highlight the point

**Comment by CrispyPin** [comment]
Most mods are updated now, so I guess you can close this
