### ISSUE TITLE
Feature Request: Config file

### ISSUE THREAD

**Issue by jrtberlin** [geefr/beatsaber-linux-goodies#91]
Thank you for your work!
It would be a nice addition to have a config file (`~/.config/beataronirc`) where users can add the path to the beat saber install to avoid having to look it up every time. 

The text input in beataroni could save the path into the config file too, so people don't have to know about it to get the benefits.

**Comment by geefr** [comment]
Should be functional in release 1.3.
Limited testing on my end, please verify at some point and raise bugs if I messed up :)

Settings are saved to .config/beataroni/settings.json (no reason for a folder other than neatness)
(((And if anyone's on windows it's %localappdata%/beataroni/config.json)))
