### ISSUE TITLE
Desktop Icon and Mascot

### ISSUE THREAD

**Issue by jrtberlin** [geefr/beatsaber-linux-goodies#92]
I've written a [PKGBUILD for the AUR](https://aur.archlinux.org/packages/beataroni-bin/) and needed an icon for the .desktop-file. 
I asked someone I know for an icon based on “The mascot is a macaroni penguin (hence the name, no reason)”.
The result was this:
![beataroni-512](https://user-images.githubusercontent.com/14153182/133658453-b438eb48-ce70-4854-a018-3e5807171390.png)

The image is drawn by `Ticia Schiffner` and the license is CC0 in-case it is used in a place where attribution is a problem or the image requires some adjustments.
There is also a vector version of the file: https://gist.github.com/jrtberlin/f8338fd6a81de99ebf729cb393c68ff0

**Comment by geefr** [comment]
Updated and merged, many thanks.

**Comment by jrtberlin** [comment]
Updated the AUR version to 1.2.2
