### ISSUE TITLE
Beatsaber version 1.24.1 missing from list

### ISSUE THREAD

**Issue by xaetacorenet** [geefr/beatsaber-linux-goodies#99]
After the new update 1.24.1 is not showing up in beateroni, is it possible to add this version?

**Comment by xaetacorenet** [comment]
I see that this is fetched from
```
    private static readonly string APIVersion = "https://versions.beatmods.com/versions.json";
```
So im closing the ticket since the problem is not in this software

**Comment by geefr** [comment]
Yep you got it, just be patient 🙂

Once beatmods is updated (once mods work again on windows) beataroni should also, there's no magic here past running on Linux.

**Comment by anxest** [comment]
Modassistant already installs 1.24.1 mods on windows, but beatmods only offerts 1.21 mods. I dont understand yet how that works and how to reproduce on linux

**Comment by xaetacorenet** [comment]
> Modassistant already installs 1.24.1 mods on windows, but beatmods only offerts 1.21 mods. I dont understand yet how that works and how to reproduce on linux

1.21 is an alias for 1.24.1 i spoke to the devs of bsmg, when having 1.21 selected it works just fine

**Comment by anxest** [comment]
Oh ! I couldn't use the mods on 1.24.1 yesterday, by installing the 1.21 mods. So my issue is somewhere else then. Thanks for your answer !

**Comment by xaetacorenet** [comment]
> Oh ! I couldn't use the mods on 1.24.1 yesterday, by installing the 1.21 mods. So my issue is somewhere else then. Thanks for your answer !

Some mods might have not ported yet, mapping extensions, beatsaver voter, downloader mods are working i confirmed this
